### ISSUE TITLE
Add comments to improve understanding

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/mimir-worker-k8s-operator#29]
Wdyt about adding a line or two for a comment per role, giving charm-related context?
If this enum class is duplicated in the coordinator as well, then perhaps a discourse post to link to from here?

The idea is not comments like `alertmanager is responsible for alerts`, but rather something like (hypothetical): `alertmanager is already included in 'all', and is a no-op if a 'ruler' is missing`.

Separate issue probably :)

_Originally posted by @sed-i in https://github.com/canonical/mimir-worker-k8s-operator/pull/28#discussion_r1511545169_

**Comment by lucabello** [comment]
This was done in https://github.com/canonical/mimir-worker-k8s-operator/pull/35
