### ISSUE TITLE
integration CI is flaky - cause unknown

### ISSUE THREAD

**Issue by ca-scribner** [canonical/mimir-worker-k8s-operator#71]
### Bug Description

We are seeing integration test failures like [here](https://github.com/canonical/mimir-worker-k8s-operator/actions/runs/10452481149/job/28941009318) with unknown causes.  We should investigate and figure it out.  It might be related to [this failed test in mimir-coordinator](https://github.com/canonical/mimir-coordinator-k8s-operator/pull/70)?

### To Reproduce

?

### Environment

ci

### Relevant log output

```shell
https://github.com/canonical/mimir-worker-k8s-operator/actions/runs/10452481149/job/28941009318
```

**Comment by lucabello** [comment]
The deployments issue should be fixed by https://github.com/canonical/cos-lib/pull/70.

Closing for now!
